{% set name = "napari-accelerated-pixel-and-object-classification" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-accelerated-pixel-and-object-classification-{{ version }}.tar.gz
  sha256: b6b012b59b261750723909d9b37e38ab67e6283fb67ea8920ca8cba974e089b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - apoc-backend >=0.6.2
    - napari-plugin-engine >=0.1.4
    - napari-time-slicer
    - napari-tools-menu
    - numpy
    - python >=3.7
    - superqt

test:
  imports:
    - napari_accelerated_pixel_and_object_classification
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-accelerated-pixel-and-object-classification
  summary: Pixel and label classification using OpenCL-based Random Forest Classifiers
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - haesleinhuepf
