{% set name = "napari-accelerated-pixel-and-object-classification" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-accelerated-pixel-and-object-classification-{{ version }}.tar.gz
  sha256: 563bee80ede325b935f80ed8ae627cc9e415eb8044213c27e58bd939dc380a55

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - apoc-backend >=0.8.1
    - napari-plugin-engine >=0.1.4
    - napari-time-slicer
    - napari-tools-menu >=0.1.16
    - numpy
    - python >=3.7
    - superqt

test:
  imports:
    - napari_accelerated_pixel_and_object_classification
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-accelerated-pixel-and-object-classification
  summary: Pixel and label classification using OpenCL-based Random Forest Classifiers
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
